services:
  license-server:
    build:
      context: ./license_portal
    links:
      - postgres
    volumes:
      - ./license_portal:/app
    ports:
        - "8000:8000"

  postgres:
    image: 'postgres:13'
    environment:
     POSTGRES_USER: 'licenses'
     POSTGRES_PASSWORD: 'licenses'
     POSTGRES_DB: 'licenses'

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"   # RabbitMQ Port
      - "15672:15672" # Admin interface RabbitMQ Port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest